// CDDL (Concise Data Definition Language) utilities for CWT.cam
// Handles import/export of CDDL schema files for CWT claims

// Export schema to CDDL format
function exportSchema(schema) {
    let cddl = '; CBOR Web Token Claims Definition\n';
    cddl += '; Generated by CWT.cam v2\n';
    cddl += '; RFC 8392 compliant CDDL\n\n';
    cddl += 'CWT_Claims = {\n';
    
    // Add standard claims with proper types
    if (schema[1]) cddl += '  ? 1 => tstr,              ; iss: Issuer\n';
    if (schema[2]) cddl += '  ? 2 => tstr,              ; sub: Subject\n';
    if (schema[3]) cddl += '  ? 3 => tstr / [+ tstr],   ; aud: Audience\n';
    if (schema[4]) cddl += '  ? 4 => ~time,             ; exp: Expiration Time\n';
    if (schema[5]) cddl += '  ? 5 => ~time,             ; nbf: Not Before\n';
    if (schema[6]) cddl += '  ? 6 => ~time,             ; iat: Issued At\n';
    if (schema[7]) cddl += '  ? 7 => bytes,             ; cti: CWT ID\n';
    
    // Add IANA and custom claims
    const otherClaims = Object.entries(schema)
        .filter(([k, v]) => parseInt(k) > 7)
        .sort(([a], [b]) => parseInt(a) - parseInt(b));
    
    otherClaims.forEach(([key, claim]) => {
        // Try to infer type from claim name/description
        let type = 'any';
        if (claim.name.includes('time') || claim.name.includes('_at')) type = '~time';
        else if (claim.name.includes('hash')) type = 'bytes';
        else if (claim.name.includes('uri') || claim.name.includes('url')) type = 'tstr';
        else if (claim.name === 'scope' || claim.name === 'permissions') type = '[* tstr]';
        
        cddl += `  ? ${key} => ${type},`;
        cddl += `${' '.repeat(Math.max(1, 18 - key.length - type.length))}; ${claim.name}: ${claim.description}\n`;
    });
    
    cddl += '  * int / tstr => any       ; Additional extension claims\n';
    cddl += '}\n\n';
    cddl += '~time = #6.1(number)\n';
    
    return cddl;
}

// Download CDDL schema as file
function downloadCDDL(schema) {
    const cddl = exportSchema(schema);
    const blob = new Blob([cddl], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'cwt-claims.cddl';
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
}

// Parse CDDL text
function parseCDDL(cddlText) {
    // Extract claims using our simple parser
    // Note: Basic validation only - does not validate full CDDL syntax
    return extractClaimsFromValidCDDL(cddlText);
}

// Extract claims from CDDL text
function extractClaimsFromValidCDDL(cddl) {
    const claims = {};
    const lines = cddl.split('\n');
    
    for (const line of lines) {
        // Skip comments and empty lines
        if (!line.trim() || line.trim().startsWith(';')) continue;
        
        // Match claim definitions: ? <number> => <type>, ; <name>: <description>
        const claimMatch = line.match(/\?\s*(\d+)\s*=>\s*[^,]+,?\s*;\s*(\w+):\s*(.+)/);
        if (claimMatch) {
            const [, key, name, description] = claimMatch;
            const claimKey = parseInt(key);
            
            // Skip standard claims 1-7 (they're built-in)
            if (claimKey > 7) {
                claims[claimKey] = {
                    name: name.trim(),
                    description: description.trim()
                };
            }
        }
    }
    
    return claims;
}

// Import CDDL schema from file
function importCDDL(onSuccess, onError) {
    const input = document.createElement('input');
    input.type = 'file';
    input.accept = '.cddl';
    input.onchange = function(e) {
        const file = e.target.files[0];
        if (!file) return;
        
        const reader = new FileReader();
        reader.onload = function(e) {
            try {
                const parsedClaims = parseCDDL(e.target.result);
                onSuccess(parsedClaims);
            } catch (error) {
                onError(error);
            }
        };
        reader.readAsText(file);
    };
    input.click();
}

// Export for use in main application
window.cddlUtils = {
    exportSchema,
    downloadCDDL,
    parseCDDL,
    importCDDL
};